export enum SessionMaterialType {
  'PRETEST' = 'PRETEST',
  'QUIZ' = 'QUIZ',
  'POSTTEST' = 'POSTTEST',
  'OFFLINECLASS' = 'OFFLINECLASS',
  'ONLINECLASS' = 'ONLINECLASS',
  'ASSIGNMENT' = 'ASSIGNMENT',
  'SKILLTEST' = 'SKILLTEST'
}
